#! /usr/bin/env ruby
# This console script adapted from:rake
#   http://barkingiguana.com/blog/2009/01/25/scriptconsole-for-your-application/

libs = []
libs << "irb/completion"
libs << File.expand_path(File.join(File.dirname(__FILE__),'env.rb'))

command_line = ["bundle exec irb -I lib -I app"]
command_line << libs.inject("") { |acc, lib| acc + %( -r "#{lib}") }
command_line << "--simple-prompt"
command = command_line.join(" ")

exec command
